#!/usr/bin/env python3
"""Generate the RQ3/RQ4 LaTeX tables from the full-budget run artifacts.

Reads exp/full_budget/results.csv (written by exp/parallel_nsga2.py) and
emits paper/ispa2026/tables/*.tex, which main.tex \\input{}s. Generating the
tables keeps the paper's numbers traceable to the run records instead of
hand-copied, and re-running this after a re-run of the experiment updates
the paper in one step.

Usage:
    python3 paper/ispa2026/make_tables.py [--results exp/full_budget/results.csv]
"""

from __future__ import annotations

import argparse
import csv
import statistics
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parent
REPO = PAPER_DIR.parent.parent
DEFAULT_RESULTS = REPO / "exp" / "full_budget" / "results.csv"

# Scale ladder, smallest to largest; the RQ4 table reports one row per case.
SCALE_ORDER = ["S025", "WEN38", "S050", "M100"]
NODE_COUNT = {"S025": 25, "WEN38": 38, "S050": 50, "M100": 100}
RQ3_SEEDS = (11, 22, 33)
RQ4_SEEDS = (11, 22)


def load(path: Path) -> list[dict]:
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        for k in (
            "solver_seed", "max_evaluations", "pop_size", "workers",
            "evaluations", "cache_hits", "front_size",
        ):
            r[k] = int(r[k])
        for k in ("runtime_seconds", "hypervolume", "igd", "max_abs_delta_vs_serial"):
            r[k] = float(r[k])
        r["front_identical_to_serial"] = r["front_identical_to_serial"] == "True"
    return rows


def mean_sd(values: list[float]) -> tuple[float, float]:
    if len(values) == 1:
        return values[0], 0.0
    return statistics.fmean(values), statistics.stdev(values)


def fmt(x: float, digits: int = 1) -> str:
    return f"{x:.{digits}f}"


def rq3_table(rows: list[dict]) -> str:
    """WEN38 full matrix, W in {0,1,2,4,8}, seeds 11/22/33."""
    cells = [r for r in rows if r["case_id"] == "WEN38" and r["solver_seed"] in RQ3_SEEDS]
    if not cells:
        raise SystemExit("no WEN38 RQ3 rows found")
    budgets = {r["max_evaluations"] for r in cells}
    assert len(budgets) == 1, f"mixed budgets in RQ3 slice: {budgets}"
    budget = budgets.pop()

    by_w: dict[int, list[dict]] = {}
    for r in cells:
        by_w.setdefault(r["workers"], []).append(r)

    serial = mean_sd([r["runtime_seconds"] for r in by_w[0]])[0]
    w1 = mean_sd([r["runtime_seconds"] for r in by_w[1]])[0]

    lines = [
        "% Generated by paper/ispa2026/make_tables.py -- do not edit by hand.",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "$W$ & Time (s) & $S_0$ & $S_1$ & $E(W)$ \\\\",
        "\\midrule",
    ]
    for w in (0, 1, 2, 4, 8):
        group = by_w.get(w)
        if not group:
            continue
        t, sd = mean_sd([r["runtime_seconds"] for r in group])
        if w == 0:
            s0, s1, eff = "--", "--", "--"
        else:
            s0 = f"{serial / t:.2f}$\\times$"
            s1 = f"{w1 / t:.2f}$\\times$"
            eff = f"{w1 / t / w:.2f}"
        label = f"{w} (serial)" if w == 0 else str(w)
        lines.append(f"{label} & {fmt(t)}$\\pm${fmt(sd)} & {s0} & {s1} & {eff} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]

    # Invariance + budget accounting summary, for the caption/footnote.
    bad = [r for r in cells if not r["front_identical_to_serial"]]
    evals = {r["evaluations"] for r in cells}
    hits = sorted({r["cache_hits"] for r in cells})
    notes = [
        f"% budget={budget} pop=32 seeds={list(RQ3_SEEDS)} nodes={NODE_COUNT['WEN38']}",
        f"% non-identical fronts: {len(bad)}/{len(cells)}",
        f"% evaluations consumed: {sorted(evals)}  cache hits: {hits}",
    ]
    return "\n".join(notes + lines)


def rq4_table(rows: list[dict]) -> str:
    """Scale ladder, W in {1,2,4,8}, seeds 11/22, per-case budgets.

    Two stacked blocks (wall-clock time, then speedup) keep the table inside
    one column; A given (case, seed) has one front regardless of W, so front
    size, HV and IGD are not tabulated per worker count -- they are reported
    in the surrounding text.
    """
    labels = {1: "$W{=}1$", 2: "$W{=}2$", 4: "$W{=}4$", 8: "$W{=}8$"}
    row = "l" + "r" * 4
    lines = [
        "% Generated by paper/ispa2026/make_tables.py -- do not edit by hand.",
        f"\\begin{{tabular}}{{{row}}}",
        "\\toprule",
        "Instance & " + " & ".join(labels[w] for w in (1, 2, 4, 8)) + " \\\\",
        "\\midrule",
        "\\multicolumn{5}{l}{\\emph{Wall-clock time (s)}} \\\\",
    ]
    notes = []
    speedup_rows = []
    for case in SCALE_ORDER:
        cells = [r for r in rows if r["case_id"] == case and r["solver_seed"] in RQ4_SEEDS]
        if not cells:
            continue
        by_w: dict[int, list[dict]] = {}
        for r in cells:
            by_w.setdefault(r["workers"], []).append(r)
        base = mean_sd([r["runtime_seconds"] for r in by_w[1]])[0]

        times, speeds = [], []
        for w in (1, 2, 4, 8):
            t = mean_sd([r["runtime_seconds"] for r in by_w[w]])[0]
            times.append(fmt(t))
            speeds.append(f"{base / t:.2f}$\\times$")
        lines.append(f"{case} ({NODE_COUNT[case]}) & " + " & ".join(times) + " \\\\")
        speedup_rows.append(
            f"{case} ({NODE_COUNT[case]}) & " + " & ".join(speeds) + " \\\\"
        )

        fronts = sorted({(r["solver_seed"], r["front_size"]) for r in cells})
        hvs = sorted({round(r["hypervolume"], 4) for r in cells})
        identical = sum(1 for r in cells if r["front_identical_to_serial"])
        notes.append(
            f"% {case}: budget={max(r['max_evaluations'] for r in cells)} "
            f"identical={identical}/{len(cells)} "
            f"per-seed fronts={[(s, f) for s, f in fronts]} HV={hvs} "
            f"IGD={sorted({round(r['igd'], 4) for r in cells})}"
        )

    lines += ["\\midrule", "\\multicolumn{5}{l}{\\emph{Speedup $S(W)=T_1/T_W$}} \\\\"]
    lines += speedup_rows
    lines += ["\\bottomrule", "\\end{tabular}", ""]

    bad = [r for r in rows if not r["front_identical_to_serial"]]
    notes.insert(0, f"% non-identical fronts across all {len(rows)} runs: {len(bad)}")
    return "\n".join(notes + lines)


def rq4_speedup_summary(rows: list[dict]) -> str:
    """Per-W speedup/efficiency plus W=1 evaluation granularity (for the text).

    The granularity column is the manuscript's actual claim: parallel
    efficiency tracks how much work one dispatch carries, not the node count.
    It is a W=1 wall-clock proxy (it includes master-side operator work), so
    the text describes it as such rather than as pure simulation cost.
    """
    out = []
    for case in SCALE_ORDER:
        cells = [r for r in rows if r["case_id"] == case and r["solver_seed"] in RQ4_SEEDS]
        if not cells:
            continue
        by_w: dict[int, list[dict]] = {}
        for r in cells:
            by_w.setdefault(r["workers"], []).append(r)
        base = mean_sd([r["runtime_seconds"] for r in by_w[1]])[0]
        parts = []
        for w in (1, 2, 4, 8):
            t = mean_sd([r["runtime_seconds"] for r in by_w[w]])[0]
            parts.append(f"W={w}: {t:.1f}s S={base / t:.2f} E={base / t / w:.2f}")
        evals = {r["evaluations"] for r in by_w[1]}
        assert len(evals) == 1, f"{case}: mixed evaluation counts {evals}"
        ms_per_eval = base * 1000.0 / evals.pop()
        out.append(
            f"% {case:>5} {ms_per_eval:6.1f} ms/eval  " + "  ".join(parts)
        )
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", type=Path, default=DEFAULT_RESULTS)
    args = parser.parse_args()
    if not args.results.exists():
        raise SystemExit(f"results file not found: {args.results}")

    rows = load(args.results)
    out_dir = PAPER_DIR / "tables"
    out_dir.mkdir(exist_ok=True)
    for name, text in (
        ("rq3_parallel.tex", rq3_table(rows)),
        ("rq4_scaling.tex", rq4_table(rows)),
        ("rq4_speedup_summary.txt", rq4_speedup_summary(rows)),
    ):
        path = out_dir / name
        path.write_text(text)
        print(f"[write] {path}")
    print()
    print(rq4_speedup_summary(rows))
    bad = [r for r in rows if not r["front_identical_to_serial"]]
    print(f"\nnon-identical fronts: {len(bad)} / {len(rows)}")


if __name__ == "__main__":
    main()
